apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-config
data:
  opa-config.yaml: |
    decision_logs:
      console: true
      reporting:
        min_delay_seconds: 5
        max_delay_seconds: 10

    labels:
      app: httpap