apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-policy
data:
  authz.rego: |
    package httpapi.authz

    default allow = false

    allow if {
      "admin" in input.roles
    }

    # superAdmin → full access to everything including userManage
    allow if {
      "superAdmin" in input.roles
    }

    allow if {
      "developer" in input.roles
      input.path == "/dev"
    }

    allow if {
      "tester" in input.roles
      input.path == "/tester"
    }

    allow if {
      "viewer" in input.roles
      input.path == "/viewer"
    }
    
    decision := {
      "user": input.user_name,
      "roles": input.roles,
      "path": input.path,
      "method": input.method,
      "allow": allow
    }
    